### ISSUE TITLE
Gem config issue, rack-cache

### ISSUE THREAD

**Issue by duderonomy** [espen/balder#49]
At commit 7c0b673, I get the following message after running bundler install.
Could not find rack-cache-1.6.0 in any of the sources.

local state:

    $ grep rack-cache Gem*
    Gemfile.lock:      rack-cache (~> 1.2)
    Gemfile.lock:    rack-cache (1.6.0)
    
    $ rails -v
    Rails 3.2.22.2

local work-around:

    $ rm Gemlock.file
    $ bundle install

**Comment by espen** [comment]
Looks like rack-cache 1.6.0 was yanked from rubygems: https://rubygems.org/gems/rack-cache

I'll update the gems and push a new Gemfile.lock.
